# Generated by Django 3.0.7 on 2020-06-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_tuts', '0002_auto_20200620_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
